// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/vothanh/crm-platform/internal/infra/config"
	"github.com/vothanh/crm-platform/internal/infra/database"
	handler9 "github.com/vothanh/crm-platform/internal/modules/analytics/handler"
	handler7 "github.com/vothanh/crm-platform/internal/modules/automation/handler"
	repository7 "github.com/vothanh/crm-platform/internal/modules/automation/repository"
	service7 "github.com/vothanh/crm-platform/internal/modules/automation/service"
	handler6 "github.com/vothanh/crm-platform/internal/modules/campaign/handler"
	repository6 "github.com/vothanh/crm-platform/internal/modules/campaign/repository"
	service6 "github.com/vothanh/crm-platform/internal/modules/campaign/service"
	"github.com/vothanh/crm-platform/internal/modules/customer/domain"
	handler2 "github.com/vothanh/crm-platform/internal/modules/customer/handler"
	repository2 "github.com/vothanh/crm-platform/internal/modules/customer/repository"
	service2 "github.com/vothanh/crm-platform/internal/modules/customer/service"
	domain2 "github.com/vothanh/crm-platform/internal/modules/ingestion/domain"
	handler4 "github.com/vothanh/crm-platform/internal/modules/ingestion/handler"
	repository3 "github.com/vothanh/crm-platform/internal/modules/ingestion/repository"
	service4 "github.com/vothanh/crm-platform/internal/modules/ingestion/service"
	"github.com/vothanh/crm-platform/internal/modules/notification"
	handler8 "github.com/vothanh/crm-platform/internal/modules/notification/handler"
	repository8 "github.com/vothanh/crm-platform/internal/modules/notification/repository"
	service8 "github.com/vothanh/crm-platform/internal/modules/notification/service"
	handler5 "github.com/vothanh/crm-platform/internal/modules/segmentation/handler"
	repository5 "github.com/vothanh/crm-platform/internal/modules/segmentation/repository"
	service5 "github.com/vothanh/crm-platform/internal/modules/segmentation/service"
	"github.com/vothanh/crm-platform/internal/modules/tenant/handler"
	"github.com/vothanh/crm-platform/internal/modules/tenant/repository"
	"github.com/vothanh/crm-platform/internal/modules/tenant/service"
	handler3 "github.com/vothanh/crm-platform/internal/modules/trip/handler"
	repository4 "github.com/vothanh/crm-platform/internal/modules/trip/repository"
	service3 "github.com/vothanh/crm-platform/internal/modules/trip/service"
)

// Injectors from wire.go:

// InitializeApp sets up the entire application using Google Wire.
func InitializeApp(cfg *config.Config) (*App, error) {
	string2 := provideDBConfig(cfg)
	db, err := database.NewPostgresDB(string2)
	if err != nil {
		return nil, err
	}
	tenantRepository := repository.NewTenantPostgresRepo(db)
	apiKeyRepository := repository.NewAPIKeyPostgresRepo(db)
	tenantService := service.NewTenantService(tenantRepository, apiKeyRepository)
	tenantHandler := handler.NewTenantHandler(tenantService)
	customerRepository := repository2.NewCustomerPostgresRepo(db)
	customerService := service2.NewCustomerService(customerRepository)
	eventRepository := repository3.NewEventPostgresRepo(db)
	eventReader := provideEventReader(eventRepository)
	customerHandler := handler2.NewCustomerHandler(customerService, eventReader)
	tripRepository := repository4.NewTripPostgresRepo(db)
	tripService := service3.NewTripService(tripRepository)
	tripHandler := handler3.NewTripHandler(tripService)
	customerActuator := provideCustomerActuator(customerService)
	tripActuator := provideTripActuator(tripService)
	ingestionService := service4.NewIngestionService(eventRepository)
	ingestionHandler := handler4.NewIngestionHandler(customerActuator, tripActuator, ingestionService)
	segmentRepository := repository5.NewSegmentPostgresRepo(db)
	customerSegmentRepository := repository5.NewCustomerSegmentPostgresRepo(db)
	segmentationService := service5.NewSegmentationService(segmentRepository, customerSegmentRepository)
	segmentationHandler := handler5.NewSegmentationHandler(segmentationService)
	campaignRepository := repository6.NewCampaignPostgresRepo(db)
	voucherRepository := repository6.NewVoucherPostgresRepo(db)
	voucherUsageRepository := repository6.NewVoucherUsagePostgresRepo(db)
	campaignService := service6.NewCampaignService(campaignRepository, voucherRepository, voucherUsageRepository)
	campaignHandler := handler6.NewCampaignHandler(campaignService)
	automationRuleRepository := repository7.NewAutomationRulePostgresRepo(db)
	automationLogRepository := repository7.NewAutomationLogPostgresRepo(db)
	automationService := service7.NewAutomationService(automationRuleRepository, automationLogRepository)
	automationHandler := handler7.NewAutomationHandler(automationService)
	notificationRepository := repository8.NewNotificationPostgresRepo(db)
	v := notification.ProvideNotificationProviders()
	notificationService := service8.NewNotificationService(notificationRepository, v)
	notificationHandler := handler8.NewNotificationHandler(notificationService)
	analyticsHandler := handler9.NewAnalyticsHandler(db)
	app, err := NewAppWithDependencies(cfg, db, tenantHandler, customerHandler, tripHandler, ingestionHandler, segmentationHandler, campaignHandler, automationHandler, notificationHandler, analyticsHandler)
	if err != nil {
		return nil, err
	}
	return app, nil
}

// wire.go:

// CrossModuleBindings provides interfaces that span across different modules.
var CrossModuleBindings = wire.NewSet(
	provideCustomerActuator,
	provideTripActuator,
	provideEventReader,
)

func provideCustomerActuator(svc domain.CustomerService) handler4.CustomerActuator {
	return svc
}

func provideTripActuator(svc *service3.TripService) handler4.TripActuator {
	return svc
}

func provideEventReader(repo domain2.EventRepository) handler2.EventReader {
	return repo
}

// provideDBConfig extracts the DSN string from the config.
func provideDBConfig(cfg *config.Config) string {
	return cfg.Database.DSN()
}
